name: food_delivery_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.3.0
  animated_bottom_navigation_bar: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets\imgs\
    - assets\icons\

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/sen/Sen-Regular.ttf
        - asset: assets/fonts/sen/Sen-Medium.ttf
          weight: 400
        - asset: assets/fonts/sen/Sen-Bold.ttf
          weight: 500
        - asset: assets/fonts/sen/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sen/Sen-ExtraBold.ttf
          weight: 700
    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster/Lobster-Regular.ttf
          weight: 700      
       
 
  

